### ISSUE TITLE
Render each Medium into a card

### ISSUE THREAD

**Issue by mihomihouk** [mihomihouk/Subly-Challenge#2]
## Task
- [x] Create Card component
- [x] Render the fetched data into the component
## Information to include on a card
- [x] Cover image
- [x] Title
- [x] Status/Last edited
